Feature/sc 319/user profile detail view
KSG-IT/ksg-nett-frontend pull request #49
Opened 2022-09-07 22:47 UTC by Plebbimon

More detailed User-view which shows user's information, quotes that they've been tagged in and their history of group memberships.

2022-09-08 07:29 UTC, Plebbimon commented
https://www.google.com/search?channel=fs&client=ubuntu&q=function+vs+react+fc
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/



"React.FunctionComponent is explicit about the return type, while the normal function version is implicit (or else needs additional annotation).

It provides typechecking and autocomplete for static properties like displayName, propTypes, and defaultProps.

    Note that there are some known issues using defaultProps with React.FunctionComponent. See [this issue for details](https://github.com/typescript-cheatsheets/react/issues/87). We maintain a separate defaultProps section you can also look up."


Still salty about this

2022-09-09 10:33 UTC, Plebbimon reviewed
Mostly additions, some which have to be refactored (functions)

2022-09-09 10:33 UTC, Plebbimon commented on src/modules/users/types.ts
> +}
Maybe this isn't the most appropriate place to put this interface

2022-09-09 11:05 UTC, Plebbimon commented on src/modules/users/UserDetail.tsx
> +}
Removed a component. Might consider extracting the card-part into a separate component so that the view doesn't get cluttered up.

2022-09-11 14:07 UTC, alexaor requested changes

2022-09-11 14:07 UTC, alexaor commented on src/modules/users/components/UserQuotes.tsx
> +}
Above component

2022-09-12 18:53 UTC, Plebbimon commented on src/modules/users/components/UserQuotes.tsx
> +}
Put it where its belongs

2022-09-12 18:53 UTC, Plebbimon commented on src/modules/users/UserDetail.tsx
> +  }
Moved it to a component

2022-09-12 18:53 UTC, Plebbimon commented on src/modules/users/UserDetail.tsx
> +    return <span>Bruker eksisterer ikke</span>
Using 404 component

2022-09-12 18:54 UTC, Plebbimon commented on src/modules/users/UserDetail.tsx
> +  if (!data || error) return <span>Something went wrong</span>
Swapped placement and `!data` condition

2022-09-12 18:54 UTC, Plebbimon commented on src/modules/users/UserDetail.tsx
> +}
Moved right above component

2022-09-28 08:21 UTC, merged