chore: added `nickname` to user edit field
KSG-IT/ksg-nett-frontend pull request #87
Opened 2022-12-21 01:10 UTC by Plebbimon

also fixed `InternalGroupSelect` component

I'm not completely done here btw, need to put the `InputLeftLabel` component somewhere else.

2022-12-21 02:16 UTC, Plebbimon commented
cHeCkmark*

2022-12-21 16:00 UTC, alexaor requested changes

2022-12-21 16:00 UTC, alexaor commented on src/modules/users/components/UserEditForm/useUserEditAPI.ts
> +    nickname: user?.nickname ?? 'drit',
set fallback to blank string

2022-12-21 16:00 UTC, alexaor commented on src/modules/users/components/UserEditForm/useUserEditLogic.ts
> +  nickname: yup.string().required('Kallenavn må fylles ut'),
should this be mandatory?

2022-12-21 16:07 UTC, Plebbimon commented on src/modules/summaries/components/SummaryForm/SummaryForm.tsx
> +                    setInternalGroup(value)
okeydokey

2022-12-21 16:12 UTC, Plebbimon commented on src/modules/users/components/UserEditForm/useUserEditLogic.ts
> +  nickname: yup.string().required('Kallenavn må fylles ut'),
No :)))

2022-12-27 21:40 UTC, alexaor approved these changes
LGTM

2022-12-27 21:40 UTC, merged